// Code generated by goctl. DO NOT EDIT.
package types

type Account struct {
	Id      int64  `json:"id"`      //id
	UserId  int64  `json:"userId"`  //用户id
	Balance string `json:"balance"` //地址
	Loan    string `json:"loan"`    //贷款
}

type AccountListResp struct {
	AccountList []UserAccountResp `json:"accountList"` //地址集合
}

type Address struct {
	Id      int64             `json:"id"`      //id
	UserId  int64             `json:"userId"`  //用户id
	Address string            `json:"address"` //地址
	Status  UserAddressStatus `json:"status"`  //状态
}

type AddressListResp struct {
	AddresList []UserAddressResp `json:"addresList"` //地址集合
}

type DmlResponse struct {
	Result bool `json:"result"`
}

type GetByIdReq struct {
	Id int64 `path:"id"`
}

type GetByUserIdReq struct {
	UserId int64 `path:"userId"`
}

type UserAccountResp struct {
	Id      int64  `path:"id",json:"id"` //id
	UserId  int64  `json:"userId"`       //userId
	Balance string `json:"balance"`      //地址
	Loan    string `json:"loan"`         //贷款
}

type UserAccountUpdateReq struct {
	Id      int64  `path:"id"`      //id
	Balance string `json:"balance"` //地址
	Loan    string `json:"loan"`    //贷款
}

type UserAddRequest struct {
	Id         int64      `json:"id"`         //id
	Name       string     `json:"name"`       //用户姓名
	Age        int        `json:"age"`        //年龄
	Account    Account    `json:"account"`    //账户
	Address    []Address  `json:"address"`    //地址
	Status     UserStatus `json:"status"`     //年龄
	Phone      string     `json:"phone"`      //手机号
	CreateTime int64      `json:"createTime"` //创建时间
	UpdateTime int64      `json:"updateTime"` //更新时间
}

type UserAddressResp struct {
	Id      int64             `path:"id"`      //id
	UserId  int64             `json:"userId"`  //userId
	Address string            `json:"address"` //地址
	Status  UserAddressStatus `json:"status"`  //状态
}

type UserAddressStatus struct {
}

type UserAddressUpdateReq struct {
	Id      int64             `path:"id"`      //id
	Address string            `json:"address"` //地址
	Status  UserAddressStatus `json:"status"`  //状态
}

type UserGetByIdResp struct {
	Id         int64      `json:"id"`         //id
	Name       string     `json:"name"`       //用户姓名
	Age        int        `json:"age"`        //年龄
	Account    Account    `json:"account"`    //账户
	Address    []Address  `json:"address"`    //地址
	Status     UserStatus `json:"status"`     //年龄
	Phone      string     `json:"phone"`      //手机号
	CreateTime int64      `json:"createTime"` //创建时间
	UpdateTime int64      `json:"updateTime"` //更新时间
}

type UserStatus struct {
}

type UserUpdateRequest struct {
	Id         int64      `path:"id"`                  //id
	Name       string     `json:"name,optional"`       //用户姓名
	Age        int        `json:"age,optional"`        //年龄
	Account    Account    `json:"account,optional"`    //账户
	Address    []Address  `json:"address,optional"`    //地址
	Status     UserStatus `json:"status,optional"`     //年龄
	Phone      string     `json:"phone,optional"`      //手机号
	UpdateTime int64      `json:"updateTime,optional"` //更新时间
}
